name: CI

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          diagnostic-endpoint: "" # Disables telemetry
          upstream-cache: "https://digitallyinduced.cachix.org"
          use-flakehub: false
      - name: Run `nix build`
        run: nix build .
